version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.23
    parameters:
      GOARCH:
        type: string
      GOOS:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
            - go-mod-v1
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Build
          command: |
            GOARCH=<< parameters.GOARCH >> \
            GOOS=<< parameters.GOOS >> \
            go build \
              -o ./${CIRCLE_PROJECT_REPONAME} \
              -v \
              -ldflags="-w -s -X github.com/jedrw/circlog/cmd.version=$(git describe --tags --always)"
      - run:
          name: Package
          command: mkdir ./build && tar cvfz ./build/${CIRCLE_PROJECT_REPONAME}_${CIRCLE_TAG}_<< parameters.GOOS >>_<< parameters.GOARCH >>.tar.gz ./${CIRCLE_PROJECT_REPONAME}
      - persist_to_workspace:
          root: build
          paths:
            - ./*
  release:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Release
          command: |
            curl -v \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/jedrw/${CIRCLE_PROJECT_REPONAME}/releases \
              -d '{"tag_name":"'$CIRCLE_TAG'","draft":false,"prerelease":false}'

            RELEASE_ID=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/jedrw/${CIRCLE_PROJECT_REPONAME}/releases/tags/${CIRCLE_TAG} \
              | jq '.id') 

            for ASSET in *.gz; do
              curl -v \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "Content-Type: $(file -b --mime-type ${ASSET})" \
                https://uploads.github.com/repos/jedrw/${CIRCLE_PROJECT_REPONAME}/releases/$RELEASE_ID/assets?name=$(basename ${ASSET}) \
                --data-binary @${ASSET};
            done

workflows:
  cicd:
    jobs:
      - build:
          matrix:
            parameters:
              GOOS: ["linux", "darwin"]
              GOARCH: ["amd64", "arm64"]
          filters:
            tags:
              only: /v\d+\.\d+\.\d+/
      - release:
          context:
            - github
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\d+\.\d+\.\d+/
